DROP TABLE song;
DROP TABLE album;

CREATE TABLE album(
	AlbumID UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT album_pk PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(256) NOT NULL,
	Artist VARCHAR(256) NOT NULL,
	NumberOfTracks INT,
	DateCreated DATETIME,
	CreatedBy UNIQUEIDENTIFIER
);

CREATE TABLE song(
	SongID UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT song_pk PRIMARY KEY DEFAULT NEWID(),
	Name VARCHAR(256) NOT NULL,
	TrackNumber INT,
	AlbumID UNIQUEIDENTIFIER
	CONSTRAINT song_fk_albumid REFERENCES album(AlbumID),
	DateCreated DATETIME,
	CreatedBy UNIQUEIDENTIFIER
);

SELECT * FROM song;
SELECT * FROM album;